import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from "react";

import { portfolioApi, PortfolioSite, requestApi, WebsiteRequest } from "../api";

type Props = { token: string; onOpenRequest: (requestNumber: string) => void; onLogout: () => void };

export default function AdminPage({ token, onOpenRequest, onLogout }: Props) {
  const [sites, setSites] = useState<PortfolioSite[]>([]); const [requests, setRequests] = useState<WebsiteRequest[]>([]); const [siteUrl, setSiteUrl] = useState(""); const [screenshot, setScreenshot] = useState<File | null>(null); const [editingSite, setEditingSite] = useState<PortfolioSite | null>(null); const [editUrl, setEditUrl] = useState(""); const [editScreenshot, setEditScreenshot] = useState<File | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const [nextSites, nextRequests] = await Promise.all([portfolioApi.listAdmin(token), requestApi.listAdmin(token)]); setSites(nextSites); setRequests(nextRequests); setError(""); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Unable to load admin tools."); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  const createSite = async (event: FormEvent) => { event.preventDefault(); if (!screenshot) { setError("Choose a screenshot."); return; } setSaving(true); try { await portfolioApi.create(token, siteUrl, screenshot); setSiteUrl(""); setScreenshot(null); await load(); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Unable to add site."); } finally { setSaving(false); } };
  const removeSite = async (site: PortfolioSite) => { if (!window.confirm("Remove this portfolio site?")) return; try { await portfolioApi.remove(token, site.id); await load(); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Unable to remove site."); } };
  const editSite = async (event: FormEvent) => { event.preventDefault(); if (!editingSite) return; setSaving(true); try { await portfolioApi.update(token, editingSite.id, editUrl, editScreenshot ?? undefined); setEditingSite(null); setEditUrl(""); setEditScreenshot(null); await load(); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Unable to update site."); } finally { setSaving(false); } };
  const moveSite = async (site: PortfolioSite, direction: -1 | 1) => { const index = sites.findIndex((item) => item.id === site.id); const swapIndex = index + direction; if (swapIndex < 0 || swapIndex >= sites.length) return; const ordered = [...sites]; [ordered[index], ordered[swapIndex]] = [ordered[swapIndex], ordered[index]]; setSites(ordered); try { await portfolioApi.reorder(token, ordered.map((item) => item.id)); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Unable to reorder sites."); await load(); } };
  const chooseScreenshot = (event: ChangeEvent<HTMLInputElement>) => setScreenshot(event.target.files?.[0] ?? null);
  return <section className="section"><div className="section-heading"><div><p className="eyebrow">Admin tools</p><h2>Portfolio and requests</h2></div><button className="secondary-button" type="button" onClick={onLogout}>Sign out</button></div>{error ? <p className="error">{error}</p> : null}<div className="panel"><h3>Add portfolio site</h3><form className="form-grid" onSubmit={createSite}><label>Site URL<input required type="url" placeholder="https://example.com" value={siteUrl} onChange={(event) => setSiteUrl(event.target.value)} /></label><label>Homepage screenshot<input required type="file" accept="image/*" onChange={chooseScreenshot} /></label><div className="wide"><button className="primary-button" disabled={saving} type="submit">{saving ? "Uploading..." : "Add site"}</button></div></form></div>{editingSite ? <div className="panel"><h3>Edit portfolio site</h3><form className="form-grid" onSubmit={editSite}><label>Site URL<input required type="url" value={editUrl} onChange={(event) => setEditUrl(event.target.value)} /></label><label>Replace screenshot<input type="file" accept="image/*" onChange={(event) => setEditScreenshot(event.target.files?.[0] ?? null)} /></label><div className="actions wide"><button className="primary-button" disabled={saving} type="submit">Save site</button><button className="secondary-button" type="button" onClick={() => setEditingSite(null)}>Cancel</button></div></form></div> : null}<div className="section"><h3>Portfolio order</h3><div className="admin-list">{sites.length ? sites.map((site, index) => <div className="admin-row" key={site.id}><a href={site.siteUrl} target="_blank" rel="noreferrer">{site.siteUrl}</a><div className="actions"><button className="icon-button" aria-label="Edit site" type="button" onClick={() => { setEditingSite(site); setEditUrl(site.siteUrl); setEditScreenshot(null); }}>&#9998;</button><button className="icon-button" aria-label="Move site earlier" disabled={index === 0} type="button" onClick={() => void moveSite(site, -1)}>&#8593;</button><button className="icon-button" aria-label="Move site later" disabled={index === sites.length - 1} type="button" onClick={() => void moveSite(site, 1)}>&#8595;</button><button className="icon-button" aria-label="Remove site" type="button" onClick={() => void removeSite(site)}>&#215;</button></div></div>) : <div className="empty">Add the first homepage screenshot above.</div>}</div></div><div className="section"><h3>Website requests</h3><div className="admin-list">{requests.length ? requests.map((request) => <div className="admin-row" key={request.requestNumber}><button className="text-button" type="button" onClick={() => onOpenRequest(request.requestNumber)}>{request.customerName} · {request.status.replace("_", " ")}</button><span>{request.requestNumber}</span></div>) : <div className="empty">No requests yet.</div>}</div></div></section>;
}
